import models.Agent;
import models.Conversation;
import models.Message;
import models.MessageAttachment;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import play.test.Fixtures;
import play.test.UnitTest;
import services.AgentService;
import services.AttachmentService;

import java.nio.file.Files;
import java.time.Instant;

/**
 * JCLAW-227 coverage for the generated-image storage path. {@link AttachmentService#persistGeneratedImage}
 * writes raw bytes straight to the conversation-keyed directory (no staging) and persists the
 * {@link MessageAttachment} row flagged {@code generated=true} with its {@code generationMetadata}. The
 * full {@code /api/conversations/{id}/messages} serialization round trip (which now also emits
 * {@code generated}) is exercised end-to-end by the {@code generate_image} tool test (JCLAW-228).
 */
class GeneratedImageStorageTest extends UnitTest {

    @BeforeEach
    void setUp() {
        Fixtures.deleteDatabase();
    }

    @AfterEach
    void tearDown() {
        // Remove any agent workspace the test planted.
        try {
            var root = AgentService.workspaceRoot();
            if (Files.exists(root)) {
                try (var stream = Files.walk(root)) {
                    stream.sorted(java.util.Comparator.reverseOrder())
                            .forEach(p -> { try { Files.deleteIfExists(p); } catch (Exception _) {} });
                }
            }
        } catch (Exception _) {
            // Best-effort — leftover dirs only add noise, not failures.
        }
    }

    @Test
    void persistGeneratedImageFlagsRowAndWritesBytes() {
        var agent = new Agent();
        agent.name = "imagegen-store-test";
        agent.modelProvider = "openrouter";
        agent.modelId = "gpt-4.1";
        agent.enabled = true;
        agent.save();

        var conv = new Conversation();
        conv.agent = agent;
        conv.channelType = "web";
        conv.peerId = "local";
        conv.save();

        var msg = new Message();
        msg.conversation = conv;
        msg.role = "assistant";
        msg.content = "here is your image";
        msg.createdAt = Instant.now();
        msg.save();

        var bytes = new byte[]{(byte) 0x89, 'P', 'N', 'G', 0, 1, 2, 3, 4};
        var meta = "{\"prompt\":\"a red bicycle\",\"model\":\"gpt-image-1\",\"provider\":\"openai\"}";

        var att = AttachmentService.persistGeneratedImage(agent, msg, bytes, "image/png", meta);

        assertTrue(att.generated, "persisted attachment must be flagged generated");
        assertEquals(meta, att.generationMetadata);
        assertEquals(MessageAttachment.KIND_IMAGE, att.kind);
        assertEquals("image/png", att.mimeType);
        assertEquals(bytes.length, att.sizeBytes);
        assertTrue(att.originalFilename.startsWith("generated-"), att.originalFilename);
        assertTrue(att.originalFilename.endsWith(".png"), att.originalFilename);

        // The bytes round-trip off disk via the same reader the vision/download paths use.
        assertArrayEquals(bytes, AttachmentService.readBytes(att), "generated bytes must read back from disk");

        // And the row is queryable by uuid with the flag intact.
        var reloaded = MessageAttachment.findByUuid(att.uuid);
        assertNotNull(reloaded, "generated attachment must be findable by uuid");
        assertTrue(reloaded.generated);
        assertEquals(meta, reloaded.generationMetadata);
    }

    @Test
    void persistGeneratedImageRejectsEmptyBytes() {
        var agent = new Agent();
        agent.name = "imagegen-empty-test";
        agent.modelProvider = "openrouter";
        agent.modelId = "gpt-4.1";
        agent.enabled = true;
        agent.save();
        var conv = new Conversation();
        conv.agent = agent;
        conv.channelType = "web";
        conv.peerId = "local";
        conv.save();
        var msg = new Message();
        msg.conversation = conv;
        msg.role = "assistant";
        msg.content = "x";
        msg.createdAt = Instant.now();
        msg.save();

        assertThrows(IllegalArgumentException.class,
                () -> AttachmentService.persistGeneratedImage(agent, msg, new byte[0], "image/png", null),
                "empty bytes must be rejected");
    }
}
