<script setup lang="ts">
/**
 * Donut breakdown of prompt composition (JCLAW-690 follow-up).
 *
 * Renders one arc per entry, sized by token share, with a legend carrying the
 * exact numbers. Deliberately hand-rolled SVG rather than a chart dependency —
 * the same call the LatencyOverlayChart makes, and a single-series donut is a
 * few `stroke-dasharray` sums.
 *
 * Every entry gets its own arc — there is no "Other" bucket. A prompt runs to
 * ~20 contributors and most are under 2%, so the tail is a band of slivers, but
 * collapsing it hid the very thing the chart is read for: where the bytes went.
 * The legend is the readable surface for the tail, and it names the same columns
 * as the table view so the two read the same way.
 */
import { computed } from 'vue'
import type { PromptBreakdownEntry } from '~/types/api'

const props = withDefaults(defineProps<{
  entries: PromptBreakdownEntry[]
  /** Denominator for share %. Omit to normalise within this series, which is
   *  what the prompt breakdown does — its one chart already spans every
   *  contributor, so the arcs should close at exactly 100%. Pass an explicit
   *  total only when a series is a known part of a larger whole. */
  total?: number
  label: string
}>(), { total: 0 })

// Curated palette for the leading slices — the arcs big enough to identify by
// colour alone. Picked to stay distinguishable in both themes and to avoid the
// red reserved for destructive affordances elsewhere in the admin UI. Each
// pairs a light-theme shade clearing 3:1 on the light surface with the dark tone.
const COLORS = [
  'light-dark(oklch(60% 0.118 184.704), #2dd4bf)',
  'light-dark(oklch(54.6% 0.245 262.881), #60a5fa)',
  'light-dark(oklch(54.1% 0.281 293.009), #a78bfa)',
  'light-dark(oklch(59.1% 0.293 322.896), #f0abfc)',
  'light-dark(oklch(55.5% 0.163 48.998), #fbbf24)',
  'light-dark(oklch(59.6% 0.145 163.225), #34d399)',
  'light-dark(oklch(51.1% 0.262 276.966), #818cf8)',
  'light-dark(oklch(64.6% 0.222 41.116), #fb923c)',
  'light-dark(oklch(60.9% 0.126 221.723), #22d3ee)',
  'light-dark(oklch(53.2% 0.157 131.589), #a3e635)',
  'light-dark(oklch(59.2% 0.249 0.584), #f472b6)',
  'light-dark(oklch(55.4% 0.046 257.417), #94a3b8)',
]

// Past the curated set the series is an open-ended tail, so colours are
// generated by golden-angle hue rotation rather than wrapping the palette with
// `% length` (which repeats a colour inside one chart). Consecutive indices are
// adjacent arcs — slices are sorted by size — and the golden angle puts them
// almost opposite each other on the wheel, which is exactly the pair that has
// to stay tellable apart.
const GOLDEN_ANGLE = 137.508

function sliceColor(i: number): string {
  const curated = COLORS[i]
  if (curated) return curated
  // Start the generated ramp off 0° so it doesn't open on destructive-red.
  const hue = (30 + (i - COLORS.length + 1) * GOLDEN_ANGLE) % 360
  const h = hue.toFixed(1)
  return `light-dark(hsl(${h}, 62%, 34%), hsl(${h}, 62%, 62%))`
}

const RADIUS = 60
const STROKE = 26
const CIRCUMFERENCE = 2 * Math.PI * RADIUS

const seriesTotal = computed(() => props.entries.reduce((n, e) => n + e.tokens, 0))
/** Share denominator: explicit total when given, else the series itself. Guarded
 *  against 0 so an all-empty series renders a track rather than dividing by zero. */
const denominator = computed(() => props.total || seriesTotal.value || 1)

const slices = computed(() => {
  const ranked = [...props.entries].filter(e => e.tokens > 0).sort((a, b) => b.tokens - a.tokens)
  // Walk a running offset so each arc starts where the previous ended.
  let offset = 0
  return ranked.map((e, i) => {
    const fraction = e.tokens / denominator.value
    const arc = {
      name: e.name,
      chars: e.chars,
      tokens: e.tokens,
      color: sliceColor(i),
      fraction,
      dash: fraction * CIRCUMFERENCE,
      offset: -offset * CIRCUMFERENCE,
    }
    offset += fraction
    return arc
  })
})

// Legend flanks the donut, so it splits down the middle and reads the way the
// arcs are ordered: biggest first, down the left column, then down the right.
// The larger half goes left when the count is odd.
const legendColumns = computed(() => {
  const half = Math.ceil(slices.value.length / 2)
  return [slices.value.slice(0, half), slices.value.slice(half)]
})

const pct = (f: number) => `${(f * 100).toFixed(1)}%`

/** Text alternative for the graphic — the donut is decorative on its own, so the
 *  accessible name carries the same ranking a sighted user reads off the arcs. */
const summary = computed(() =>
  `${props.label}: ${seriesTotal.value.toLocaleString()} tokens. `
  + slices.value.map(s => `${s.name} ${pct(s.fraction)}`).join(', '))
</script>

<template>
  <div class="py-4">
    <!-- Donut between the two legend halves, all three the same height:
         `items-stretch` hands every item the row's height, which the legend
         columns alone determine (see the wrapper below), so the three tops and
         bottoms line up and nothing overhangs. Stacked below lg, where three
         columns can't hold their widths, and `order` floats the donut back above
         the legend so the graphic still leads. -->
    <div class="flex flex-col lg:flex-row items-center lg:items-stretch gap-6">
      <!--
        The wrapper keeps a definite width because flexbox resolves the main
        axis before the cross axis, so an auto-width SVG would have its width
        pinned from an intrinsic default while its height stretched.

        At lg the SVG is taken out of flow. An SVG with a viewBox and a definite
        width has an intrinsic height from its aspect ratio, and in flow that
        height sets the flex line's cross size — the donut would size the row
        and overhang the legend rather than the other way round. Absolutely
        positioned it contributes no height, so the row is measured from the
        legend columns alone and the donut fills exactly that. Its own
        preserveAspectRatio keeps the circle round and centred in the box.
      -->
      <div class="order-1 lg:order-2 shrink-0 w-56 h-56 lg:w-72 lg:h-auto lg:relative">
        <svg
          :viewBox="`0 0 ${(RADIUS + STROKE) * 2} ${(RADIUS + STROKE) * 2}`"
          class="w-full h-full lg:absolute lg:inset-0 -rotate-90"
          role="img"
          :aria-label="summary"
        >
          <circle
            :cx="RADIUS + STROKE"
            :cy="RADIUS + STROKE"
            :r="RADIUS"
            fill="none"
            stroke="currentColor"
            class="text-border"
            :stroke-width="STROKE"
          />
          <circle
            v-for="s in slices"
            :key="s.name"
            :cx="RADIUS + STROKE"
            :cy="RADIUS + STROKE"
            :r="RADIUS"
            fill="none"
            :stroke="s.color"
            :stroke-width="STROKE"
            :stroke-dasharray="`${s.dash} ${CIRCUMFERENCE - s.dash}`"
            :stroke-dashoffset="s.offset"
          >
            <title>{{ s.name }} — {{ s.tokens.toLocaleString() }} tokens ({{ pct(s.fraction) }})</title>
          </circle>
        </svg>
      </div>

      <!-- Each half carries its own header: the columns are independent lists
           side by side, so a single header over one of them would leave the
           other's numbers unlabelled. Wording matches the table view's
           Section / Chars / ≈ Tokens / % of total. -->
      <div
        v-for="(column, col) in legendColumns"
        :key="col"
        class="flex-1 min-w-0 w-full"
        :class="col === 0 ? 'order-2 lg:order-1' : 'order-3'"
      >
        <div
          class="flex items-center gap-2 pb-1 mb-1 border-b border-border
                 text-[10px] text-fg-muted uppercase tracking-wide"
          data-testid="legend-header"
        >
          <span
            class="w-2.5 shrink-0"
            aria-hidden="true"
          />
          <span class="flex-1 truncate">Section</span>
          <span class="w-16 text-right">Chars</span>
          <span class="w-16 text-right whitespace-nowrap">≈ Tokens</span>
          <span class="w-20 text-right whitespace-nowrap">% of total</span>
        </div>
        <ul class="space-y-1 text-xs">
          <li
            v-for="s in column"
            :key="s.name"
            class="flex items-center gap-2"
          >
            <span
              class="w-2.5 h-2.5 shrink-0"
              :style="{ backgroundColor: s.color }"
              aria-hidden="true"
            />
            <span class="flex-1 truncate text-fg-primary font-mono">{{ s.name }}</span>
            <span class="tabular-nums text-fg-muted w-16 text-right">{{ s.chars.toLocaleString() }}</span>
            <span class="tabular-nums text-fg-muted w-16 text-right">{{ s.tokens.toLocaleString() }}</span>
            <span class="tabular-nums text-fg-muted w-20 text-right">{{ pct(s.fraction) }}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>
